<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Report - {{ config('app.name') }}</title>
    <style>
        body { font-family: 'Helvetica', Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a365d; border-bottom: 2px solid #1a365d; padding-bottom: 10px; }
        h2 { color: #2d3748; margin-top: 20px; }
        .content { line-height: 1.6; white-space: pre-wrap; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #718096; }
    </style>
</head>
<body>
    <h1>AI Agent Report</h1>
    <p>Generated on {{ now()->format('F j, Y, g:i a') }}</p>

    <h2>Content</h2>
    <div class="content">
        {!! nl2br(e($content)) !!}
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
    </div>
</body>
</html>
